name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Set your branch name here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add your test command here
        echo "Running tests..."
        # pytest  # Uncomment and add pytest if you have tests

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ec2-44-202-160-167.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    - name: Copy files via SCP
      run: |
        scp -o StrictHostKeyChecking=no -r . ubuntu@ec2-44-202-160-167.compute-1.amazonaws.com:/home/ubuntu/LCA_python_backend

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-44-202-160-167.compute-1.amazonaws.com << 'EOF'
          cd /home/ubuntu/LCA_python_backend
          docker-compose down
          docker-compose up --build -d
        EOF
